import React from 'react';
import '../stylesheets/Layout.css'

export default function Layout(props) {
    return(
        <div className="layout-div">
            <div className="zeroes-inside-columns">
                <section className="zeroes">
                    <div className="bet-box">00 straight</div>
                    <div className="bet-box">0-00 split</div>
                    <div className="bet-box">0 straight</div>
                </section>
                <section className="inside-and-columns">
                    <div className="bet-box">00-3 split</div>
                    <div className="bet-box">3 straight</div>
                    <div className="bet-box">3-6 split</div>
                    <div className="bet-box">6 straight</div>
                    <div className="bet-box">6-9 split</div>
                    <div className="bet-box">9 straight</div>
                    <div className="bet-box">9-12 split</div>
                    <div className="bet-box">12 straight</div>
                    <div className="bet-box">12-15 split</div>
                    <div className="bet-box">15 straight</div>
                    <div className="bet-box">15-18 split</div>
                    <div className="bet-box">18 straight</div>
                    <div className="bet-box">18-21 split</div>
                    <div className="bet-box">21 straight</div>
                    <div className="bet-box">21-24 split</div>
                    <div className="bet-box">24 straight</div>
                    <div className="bet-box">24-27 split</div>
                    <div className="bet-box">27 straight</div>
                    <div className="bet-box">27-30 split</div>
                    <div className="bet-box">30 straight</div>
                    <div className="bet-box">30-33 split</div>
                    <div className="bet-box">33 straight</div>
                    <div className="bet-box">33-36 split</div>
                    <div className="bet-box">36 straight</div>
                    <div className="bet-box">3rd column</div>
                    <div className="bet-box">00-2-3 street</div>
                    <div className="bet-box">2-3 split</div>
                    <div className="bet-box">2-3-5-6 corner</div>
                    <div className="bet-box">5-6 split</div>
                    <div className="bet-box">5-6-8-9 corner</div>
                    <div className="bet-box">8-9 split</div>
                    <div className="bet-box">8-9-11-12 corner</div>
                    <div className="bet-box">11-12 split</div>
                    <div className="bet-box">11-12-14-15 corner</div>
                    <div className="bet-box">14-15 split</div>
                    <div className="bet-box">14-15-17-18 corner</div>
                    <div className="bet-box">17-18 split</div>
                    <div className="bet-box">17-18-20-21 corner</div>
                    <div className="bet-box">20-21 split</div>
                    <div className="bet-box">20-21-23-24 corner</div>
                    <div className="bet-box">23-24 split</div>
                    <div className="bet-box">23-24-26-27 corner</div>
                    <div className="bet-box">26-27 split</div>
                    <div className="bet-box">26-27-29-30 corner</div>
                    <div className="bet-box">29-30 split</div>
                    <div className="bet-box">29-30-32-33 corner</div>
                    <div className="bet-box">32-33 split</div>
                    <div className="bet-box">32-33-35-36 corner</div>
                    <div className="bet-box">35-36 split</div>
                    <div className="empty">empty</div>

                    <div className="bet-box">0 - 00 - 2 street</div>
                    <div className="bet-box">2 straight</div>
                    <div className="bet-box">2-5 split</div>
                    <div className="bet-box">5 straight</div>
                    <div className="bet-box">5-8 split</div>
                    <div className="bet-box">8 straight</div>
                    <div className="bet-box">8-11 split</div>
                    <div className="bet-box">11 straight</div>
                    <div className="bet-box">11-14 split</div>
                    <div className="bet-box">14 straight</div>
                    <div className="bet-box">14-17 split</div>
                    <div className="bet-box">17 straight</div>
                    <div className="bet-box">17-20 split</div>
                    <div className="bet-box">20 straight</div>
                    <div className="bet-box">20-23 split</div>
                    <div className="bet-box">23 straight</div>
                    <div className="bet-box">23-26 split</div>
                    <div className="bet-box">26 straight</div>
                    <div className="bet-box">26-29 split</div>
                    <div className="bet-box">29 straight</div>
                    <div className="bet-box">29-32 split</div>
                    <div className="bet-box">32 straight</div>
                    <div className="bet-box">32-35 split</div>
                    <div className="bet-box">35 straight</div>
                    <div className="bet-box">2nd column</div>
                    <div className="bet-box">0-1-2 street</div>
                    <div className="bet-box">1-2 split</div>
                    <div className="bet-box">1-2-4-5 corner</div>
                    <div className="bet-box">4-5 split</div>
                    <div className="bet-box">4-5-7-8 corner</div>
                    <div className="bet-box">7-8 split</div>
                    <div className="bet-box">7-8-10-11 corner</div>
                    <div className="bet-box">10-11 split</div>
                    <div className="bet-box">10-11-13-14 corner</div>
                    <div className="bet-box">13-14 split</div>
                    <div className="bet-box">13-14-16-17 corner</div>
                    <div className="bet-box">16-17 split</div>
                    <div className="bet-box">16-17-19-20 corner</div>
                    <div className="bet-box">19-20 split</div>
                    <div className="bet-box">19-20-22-23 corner</div>
                    <div className="bet-box">22-23 split</div>
                    <div className="bet-box">22-23-25-26 corner</div>
                    <div className="bet-box">25-26 split</div>
                    <div className="bet-box">25-26-28-29 corner</div>
                    <div className="bet-box">28-29 split</div>
                    <div className="bet-box">28-29-31-32 corner</div>
                    <div className="bet-box">31-32 split</div>
                    <div className="bet-box">31-32-34-35 corner</div>
                    <div className="bet-box">34-35 split</div>
                    <div className="empty"></div>

                    <div className="bet-box">0-1 split</div>
                    <div className="bet-box">1 straight</div>
                    <div className="bet-box">1-4 split</div>
                    <div className="bet-box">4 straight</div>
                    <div className="bet-box">4-7 split</div>
                    <div className="bet-box">7 straight</div>
                    <div className="bet-box">7-10 split</div>
                    <div className="bet-box">10 straight</div>
                    <div className="bet-box">10-13 split</div>
                    <div className="bet-box">13 straight</div>
                    <div className="bet-box">13-16 split</div>
                    <div className="bet-box">16 straight</div>
                    <div className="bet-box">16-19 split</div>
                    <div className="bet-box">19 straight</div>
                    <div className="bet-box">19-22 split</div>
                    <div className="bet-box">22 straight</div>
                    <div className="bet-box">22-25 split</div>
                    <div className="bet-box">25 straight</div>
                    <div className="bet-box">25-28 split</div>
                    <div className="bet-box">28 straight</div>
                    <div className="bet-box">28-31 split</div>
                    <div className="bet-box">31 straight</div>
                    <div className="bet-box">31-34 split</div>
                    <div className="bet-box">34 straight</div>
                    <div className="bet-box">1st column</div>
                    <div className="empty"></div>
                    <div className="bet-box">1-2-3 street</div>
                    <div className="bet-box">1 to 6 double street</div>
                    <div className="bet-box">4-5-6 street</div>
                    <div className="bet-box">4 to 9 double street</div>
                    <div className="bet-box">7-8-9 street</div>
                    <div className="bet-box">7 to 12 double street</div>
                    <div className="bet-box">10-11-12 street</div>
                    <div className="bet-box">10 to 15 double street</div>
                    <div className="bet-box">13-14-15 street</div>
                    <div className="bet-box">13 to 18 double street</div>
                    <div className="bet-box">16-17-18 street</div>
                    <div className="bet-box">16 to 21 double street</div>
                    <div className="bet-box">19-20-21 street</div>
                    <div className="bet-box">19 to 24 double street</div>
                    <div className="bet-box">22-23-24 street</div>
                    <div className="bet-box">22 to 27 double street</div>
                    <div className="bet-box">25-26-27 street</div>
                    <div className="bet-box">25 to 30 double street</div>
                    <div className="bet-box">28-29-30 street</div>
                    <div className="bet-box">28 to 33 double street</div>
                    <div className="bet-box">31-32-33 street</div>
                    <div className="bet-box">31-36 double street</div>
                    <div className="bet-box">34-35-36 street</div>
                </section>
            </div>
            <section className="dozens">
                <div className="empty"></div>
                <div className="bet-box">1st dozen</div>
                <div className="bet-box">2nd dozen</div>
                <div className="bet-box">3rd dozen</div>
            </section>
            <section className="even-money-bets">
                <div className="empty"></div>
                <div className="bet-box">1 to 18</div>
                <div className="bet-box">odd</div>
                <div className="bet-box">red</div>
                <div className="bet-box">black</div>
                <div className="bet-box">even</div>
                <div className="bet-box">19 to 36</div>
            </section>
        </div>
    )
}